---
# mackerel
- block:
    - name: Import GPG Key
      rpm_key:
        state: present
        key: https://mackerel.io/file/cert/GPG-KEY-mackerel-v2

    - name: "Install mackerel repo(CentOS7)"
      copy:
        src: "etc/yum.repos.d/mackerel.repo"
        dest: "/etc/yum.repos.d/mackerel.repo"
        owner: root
        group: root
        mode: 0644

    - name: install mackerel package
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - mackerel-agent
          - mackerel-check-plugins
          - mkr

    - name: mackerel-agent init
      command: mackerel-agent init -apikey="{{ mackerel_Api_Key }}"
      check_mode: no

    - name: Start mackerel-agent
      systemd:
        name: mackerel-agent
        state: restarted
        daemon_reload: yes
        enabled: yes

  when: mackerel_install


# ローカルのgrafana.repoファイルをコピー
- name: copy grafana.repo in /etc/yum.repos.d
  copy:
    dest: /etc/yum.repos.d
    src: etc/grafana/grafana.repo

# grafanaをインストール
- name: Install the Grafana
  yum:
    name: grafana
    state: present

# 自動起動設定の有効化とサービスの起動
- name: Systemctl enabled grafana-server & systemctl start grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes
