---
# ローカルのgrafana.repoファイルをコピー
- name: copy grafana.repo in /etc/yum.repos.d
  copy:
    dest: /etc/yum.repos.d
    src: etc/grafana/grafana.repo

# grafanaをインストール
- name: Install the Grafana
  yum:
    name: grafana
    state: present

# 自動起動設定の有効化とサービスの起動
- name: Systemctl enabled grafana-server & systemctl start grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes
